export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const WAREHOUSE_REPOSITORY = 'PRODUCT_REPOSITORY';
export const STOCK_REPOSITORY = 'STOCK_REPOSITORY';
export const TRANSFER_REPOSITORY = 'TRANSFER_REPOSITORY';
